import { CONTENT_ITEMS } from "@/data/content";
import { getContentUrl } from "@/lib/content-paths";

import type { SearchResult } from "./types";

function buildContentSearchItems(): SearchResult[] {
  return CONTENT_ITEMS.map((item) => ({
    id: `content-${item.slug}`,
    titleKey: `items.${item.slug}.title`,
    descriptionKey: `items.${item.slug}.description`,
    type: item.category,
    url: getContentUrl(item.category, item.slug),
    tags: buildTags(item.slug),
  }));
}

function buildTags(slug: string): string[] {
  const tagMap: Record<string, string[]> = {
    i18n: ["i18n", "next-intl", "internacionalização", "tradução", "deepl"],
    seo: ["seo", "meta tags", "open graph", "json-ld", "sitemap", "robots"],
    "ai-chatbot": [
      "ai",
      "chatbot",
      "openai",
      "gpt",
      "streaming",
      "assistente",
      "ia",
    ],
    "ai-tips": ["ia", "ai", "copilot", "chatgpt", "v0", "prompts"],
    "tailwind-tips": ["tailwind", "shadcn", "css", "ui", "componentes"],
    "react-query-tips": [
      "react query",
      "tanstack",
      "cache",
      "mutations",
      "estado",
    ],
    "react-router-tips": [
      "react router",
      "nested routing",
      "loaders",
      "navigation guards",
      "routing",
      "dynamic routing",
      "use params",
      "lazy loading",
      "protected routes",
    ],
    "dev-resources": [
      "recursos",
      "snippets",
      "componentes",
      "playground",
      "junior",
      "pleno",
      "senior",
    ],
    "security-tips": [
      "segurança",
      "security",
      "rate limiting",
      "recaptcha",
      "honeypot",
      "headers",
      "zod",
      "validação",
      "xss",
      "csrf",
    ],
    "privacy-tips": [
      "privacidade",
      "privacy",
      "cookies",
      "lgpd",
      "gdpr",
      "consentimento",
      "consent",
      "banner",
      "política",
      "policy",
    ],
    "code-review": [
      "code review",
      "ai",
      "ia",
      "análise",
      "bugs",
      "openai",
      "gpt",
      "reviewer",
      "qualidade",
    ],
    regex: [
      "regex",
      "expressão regular",
      "pattern",
      "regexp",
      "playground",
      "tester",
      "validação",
      "match",
    ],
    json: [
      "json",
      "formatter",
      "validator",
      "formatar",
      "validar",
      "pretty print",
      "minify",
      "api",
      "config",
    ],
    "typescript-patterns": [
      "typescript",
      "ts",
      "types",
      "generics",
      "utility types",
      "narrowing",
      "patterns",
      "tipagem",
      "tipo",
    ],
    "git-workflow": [
      "git",
      "workflow",
      "branching",
      "commit",
      "conventional",
      "cheat sheet",
      "merge",
      "rebase",
      "branch",
    ],
    "react-patterns": [
      "react",
      "patterns",
      "design patterns",
      "hooks",
      "compound",
      "composição",
      "memo",
      "performance",
      "context",
      "reducer",
    ],
    "nextjs-app-router": [
      "next.js",
      "nextjs",
      "app router",
      "routing",
      "server components",
      "client components",
      "data fetching",
      "loading",
      "error boundary",
      "layout",
      "page",
    ],
    "arch-map": [
      "arquitetura",
      "architecture",
      "mapa",
      "map",
      "diagrama",
      "diagram",
      "nodes",
      "microserviços",
      "microservices",
      "saas",
      "e-commerce",
      "dashboard",
      "real-time",
      "websocket",
      "infraestrutura",
      "infra",
      "sistema",
      "design de sistema",
      "system design",
    ],
    "code-evolution": [
      "evolução",
      "evolution",
      "refactor",
      "refatoração",
      "clean code",
      "boas práticas",
      "best practices",
      "lifecycle",
      "hooks",
      "swr",
      "zustand",
      "legado",
      "legacy",
      "melhoria",
    ],
    "state-management": [
      "estado",
      "react",
      "usestate",
      "context",
      "zustand",
      "redux",
      "state management",
      "prop drilling",
      "store",
    ],
    testing: [
      "testing",
      "testes",
      "vitest",
      "testing library",
      "unit test",
      "jest",
      "coverage",
      "mock",
      "__tests__",
    ],
    "contact-form": [
      "contato",
      "contact",
      "formulário",
      "form",
      "resend",
      "zod",
      "rate limit",
      "recaptcha",
      "email",
      "api",
    ],
    "api-security": [
      "segurança",
      "security",
      "api",
      "rate limit",
      "zod",
      "sanitização",
      "sanitization",
      "injection",
      "xss",
      "headers",
      "redis",
      "pipeline",
      "validação",
    ],
    "design-patterns": [
      "design patterns",
      "padrões",
      "patterns",
      "observer",
      "strategy",
      "factory",
      "decorator",
      "command",
      "gof",
      "typescript",
      "refactor",
      "oop",
    ],
    "a11y-guide": [
      "acessibilidade",
      "accessibility",
      "a11y",
      "aria",
      "wcag",
      "foco",
      "focus",
      "skip link",
      "semântica",
      "semantics",
      "contraste",
      "contrast",
      "screen reader",
    ],
    "pr-generator": [
      "pr",
      "pull request",
      "gerador",
      "generator",
      "ia",
      "ai",
      "descrição",
      "description",
      "template",
      "conventional commits",
      "git",
    ],
    "github-analyzer": [
      "github",
      "perfil",
      "profile",
      "análise",
      "analyzer",
      "ia",
      "ai",
      "repositórios",
      "repos",
      "linguagens",
      "languages",
      "open source",
    ],
  };
  return tagMap[slug] ?? [slug];
}

const STANDALONE_PAGES: SearchResult[] = [
  {
    id: "page-stats",
    titleKey: "items.stats.title",
    descriptionKey: "items.stats.description",
    type: "page",
    url: "/stats",
    tags: [
      "stats",
      "métricas",
      "metrics",
      "page views",
      "visitantes",
      "visitors",
      "reações",
      "reactions",
      "buscas",
      "searches",
      "redis",
      "analytics",
    ],
  },
  {
    id: "page-performance",
    titleKey: "items.performance.title",
    descriptionKey: "items.performance.description",
    type: "page",
    url: "/performance",
    tags: [
      "performance",
      "web vitals",
      "lcp",
      "inp",
      "cls",
      "fcp",
      "ttfb",
      "lighthouse",
      "core web vitals",
    ],
  },
  {
    id: "page-contribute",
    titleKey: "items.contribute.title",
    descriptionKey: "items.contribute.description",
    type: "page",
    url: "/contribua",
    tags: [
      "contribuir",
      "contribute",
      "open source",
      "comunidade",
      "community",
      "github",
      "pr",
      "pull request",
    ],
  },
  {
    id: "page-architecture",
    titleKey: "items.architecture.title",
    descriptionKey: "items.architecture.description",
    type: "page",
    url: "/contribua/arquitetura",
    tags: ["arquitetura", "architecture", "estrutura", "pastas", "padrões"],
  },
  {
    id: "page-tech-stack",
    titleKey: "items.techStack-page.title",
    descriptionKey: "items.techStack-page.description",
    type: "page",
    url: "/contribua/tech-stack",
    tags: ["tech stack", "bibliotecas", "libs", "dependências", "versões"],
  },
  {
    id: "page-design-system",
    titleKey: "items.designSystem.title",
    descriptionKey: "items.designSystem.description",
    type: "page",
    url: "/contribua/design-system",
    tags: ["design system", "componentes", "ui", "button", "card", "badge"],
  },
  {
    id: "page-api-docs",
    titleKey: "items.apiDocs.title",
    descriptionKey: "items.apiDocs.description",
    type: "page",
    url: "/contribua/api",
    tags: ["api", "endpoints", "rest", "rate limiting", "segurança"],
  },
  {
    id: "page-accessibility",
    titleKey: "items.accessibility.title",
    descriptionKey: "items.accessibility.description",
    type: "page",
    url: "/contribua/acessibilidade",
    tags: [
      "acessibilidade",
      "accessibility",
      "a11y",
      "aria",
      "wcag",
      "teclado",
    ],
  },
  {
    id: "page-tutorial",
    titleKey: "items.tutorial.title",
    descriptionKey: "items.tutorial.description",
    type: "page",
    url: "/contribua/tutorial",
    tags: [
      "tutorial",
      "guia",
      "passo a passo",
      "como contribuir",
      "iniciante",
      "setup",
      "fork",
      "pr",
      "pull request",
    ],
  },
];

const META_PAGES: SearchResult[] = [
  {
    id: "page-changelog",
    titleKey: "items.changelog.title",
    descriptionKey: "items.changelog.description",
    type: "page",
    url: "/novidades",
    tags: [
      "changelog",
      "novidades",
      "atualizações",
      "versões",
      "releases",
      "what's new",
      "melhorias",
    ],
  },
];

const LISTING_PAGES: SearchResult[] = [
  {
    id: "page-implementations",
    titleKey: "items.implementations.title",
    descriptionKey: "items.implementations.description",
    type: "page",
    url: "/implementacoes",
    tags: ["implementações", "implementations", "i18n", "seo", "chatbot"],
  },
  {
    id: "page-guides",
    titleKey: "items.guides.title",
    descriptionKey: "items.guides.description",
    type: "page",
    url: "/dicas",
    tags: [
      "dicas",
      "guias",
      "tips",
      "guides",
      "tutoriais",
      "react",
      "typescript",
      "git",
    ],
  },
  {
    id: "page-tools",
    titleKey: "items.tools.title",
    descriptionKey: "items.tools.description",
    type: "page",
    url: "/ferramentas",
    tags: [
      "ferramentas",
      "tools",
      "code review",
      "regex",
      "playground",
      "editor",
    ],
  },
];

const HOME_SECTIONS: SearchResult[] = [
  {
    id: "home-about",
    titleKey: "items.about.title",
    descriptionKey: "items.about.description",
    type: "section",
    url: "/#about",
    tags: ["sobre", "about", "experiência", "frontend", "senior", "vinicius"],
  },
  {
    id: "home-stack",
    titleKey: "items.techStack.title",
    descriptionKey: "items.techStack.description",
    type: "section",
    url: "/#stack",
    tags: [
      "tech stack",
      "tecnologias",
      "react",
      "next.js",
      "typescript",
      "tailwind",
      "node",
    ],
  },
  {
    id: "home-github",
    titleKey: "items.github.title",
    descriptionKey: "items.github.description",
    type: "section",
    url: "/#github",
    tags: [
      "github",
      "estatísticas",
      "repositórios",
      "contribuições",
      "linguagens",
    ],
  },
  {
    id: "home-projects",
    titleKey: "items.projects.title",
    descriptionKey: "items.projects.description",
    type: "section",
    url: "/#projects",
    tags: ["projetos", "github", "open source", "portfolio"],
  },
  {
    id: "home-experience",
    titleKey: "items.experience.title",
    descriptionKey: "items.experience.description",
    type: "section",
    url: "/#experience",
    tags: ["experiência", "carreira", "timeline", "empresas", "trabalho"],
  },
  {
    id: "home-ai",
    titleKey: "items.ai.title",
    descriptionKey: "items.ai.description",
    type: "section",
    url: "/#ai",
    tags: [
      "ia",
      "ai",
      "inovação",
      "copilot",
      "chatgpt",
      "inteligência artificial",
    ],
  },
  {
    id: "home-contact",
    titleKey: "items.contact.title",
    descriptionKey: "items.contact.description",
    type: "section",
    url: "/#contact",
    tags: ["contato", "email", "whatsapp", "formulário"],
  },
];

export const SEARCH_ITEMS: SearchResult[] = [
  ...META_PAGES,
  ...STANDALONE_PAGES,
  ...LISTING_PAGES,
  ...HOME_SECTIONS,
  ...buildContentSearchItems(),
];
